name: Webcast Company
favicon: null
layout_spectrum: 0.4412767437752336
typography_spectrum: 0.49458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8483180741313845
  lightness: 0.3745447651017457
  saturation: 0.2468250165693462
  rhythmicContrast: 0.08024625387042761
purpose: []
